---
- hosts: '{{ target }}'
  gather_facts: yes
  tasks:
  
  - name: TCP Buffer Sizes
    sysctl: name=net.core.rmem_max value=16777216 state=present
  
  - name: TCP Buffer Sizes
    sysctl: name=net.core.wmem_max value=16777216 state=present
  
  - name: TCP Buffer Sizes
    sysctl: name=net.ipv4.tcp_rmem value="4096 87380 16777216"  state=present
  
  - name: TCP Buffer Sizes
    sysctl: name=net.ipv4.tcp_wmem value="4096 16384 16777216"  state=present

  - name: Queue Sizes
    sysctl: name=net.core.somaxconn value=4096  state=present
  
  - name: Queue Sizes
    sysctl: name=net.core.netdev_max_backlog value=16384  state=present
  
  - name: Queue Sizes
    sysctl: name=net.ipv4.tcp_max_syn_backlog value=8192  state=present
  
  - name: Queue Sizes
    sysctl: name=net.ipv4.tcp_syncookies value=1  state=present
 
  - name: Ports
    sysctl: name=net.ipv4.ip_local_port_range value="1024 65535"  state=present
  
  - name: Ports
    sysctl: name=net.ipv4.tcp_tw_recycle value=1  state=present
  
  - name: Congestion Control
    sysctl: name=net.ipv4.tcp_available_congestion_control value=cubic state=present
  
  - name: Congestion Control
    sysctl: name=net.ipv4.tcp_congestion_control value=cubic  state=present
  
  - blockinfile:
     dest: "/etc/security/limits.conf"
     insertbefore: "^End of file"
     block: |
       root         hard nofile     40000
       root         soft nofile     40000
